[directory]
fish_style_pwd_dir_length=1

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ï´ƒ "
style = "blue bold"

[memory_usage]
disabled = false
threshold = -1
style = "bold dimmed green"
symbol = "ï¡š "
format = "$symbol[${ram}(\\${swap})]($style) "

[sudo]
style = "bold green"
symbol = "ğŸ‘©â€ğŸ’» "
disabled = false

